# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: Sarah Eadie
description: > # this means to ignore newlines until "email:"
   Writer | Leader | Inspiration 

email: eadiesn@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/background_image.jpg"

name: Sarah Eadie
author: Sarah Eadie
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://eadiesn.github.io" # the base hostname & protocol for your site
baseurl: "http://eadiesn.github.io"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/eadiest
    desc: Tweet me.
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/eadiesn
    desc:	Fork me.
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
